<?php
require_once __DIR__ . '/db.php';

/** Slugs that may never be used as page slugs (they'd collide with real files). */
const BW_RESERVED_SLUGS = [
    'index', 'page', 'setupdb', 'config', 'admin', 'includes',
    'assets', 'uploads', 'api', 'home',
];

/** HTML-escape shortcut. */
function e(?string $s): string
{
    return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8');
}

/** Base URL of the site (no trailing slash). */
function base_url(): string
{
    static $base = null;
    if ($base !== null) {
        return $base;
    }
    if (BASE_URL !== '') {
        return $base = rtrim(BASE_URL, '/');
    }
    $https  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
    $scheme = $https ? 'https' : 'http';
    $host   = $_SERVER['HTTP_HOST'] ?? 'localhost';
    // Strip /admin and the script name to find the project root.
    $dir = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/'));
    if (str_ends_with($dir, '/admin')) {
        $dir = substr($dir, 0, -6);
    }
    $dir = rtrim($dir, '/');
    return $base = $scheme . '://' . $host . $dir;
}

/** URL of a CMS page. */
function page_url(string $slug): string
{
    if ($slug === 'home') {
        return base_url() . '/';
    }
    return base_url() . '/' . rawurlencode($slug) . '.php';
}

/** Turn any string into a URL-safe slug. */
function slugify(string $text): string
{
    $map  = ['ą'=>'a','č'=>'c','ę'=>'e','ė'=>'e','į'=>'i','š'=>'s','ų'=>'u','ū'=>'u','ž'=>'z',
             'Ą'=>'a','Č'=>'c','Ę'=>'e','Ė'=>'e','Į'=>'i','Š'=>'s','Ų'=>'u','Ū'=>'u','Ž'=>'z'];
    $text = strtr($text, $map);
    $text = strtolower(trim($text));
    $text = preg_replace('/[^a-z0-9]+/', '-', $text);
    return trim($text, '-');
}

/** Read a site setting (cached per request). */
function setting(string $key, string $default = ''): string
{
    static $cache = null;
    if ($cache === null) {
        $cache = [];
        try {
            foreach (q_all('SELECT skey, svalue FROM settings') as $row) {
                $cache[$row['skey']] = $row['svalue'];
            }
        } catch (Throwable $e) {
            // Table may not exist yet (before setupdb.php runs).
        }
    }
    return $cache[$key] ?? $default;
}

/** Write a site setting. */
function set_setting(string $key, string $value): void
{
    q('INSERT INTO settings (skey, svalue) VALUES (?, ?)
       ON DUPLICATE KEY UPDATE svalue = VALUES(svalue)', [$key, $value]);
}

/** Extract a YouTube video ID from any common URL form. */
function youtube_id(string $url): string
{
    if (preg_match('~(?:youtu\.be/|v=|embed/|shorts/|live/)([A-Za-z0-9_-]{6,20})~', $url, $m)) {
        return $m[1];
    }
    return preg_match('/^[A-Za-z0-9_-]{6,20}$/', trim($url)) ? trim($url) : '';
}

// ---------------------------------------------------------------------------
// CSRF
// ---------------------------------------------------------------------------

function csrf_token(): string
{
    if (empty($_SESSION['csrf'])) {
        $_SESSION['csrf'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['csrf'];
}

function csrf_field(): string
{
    return '<input type="hidden" name="csrf" value="' . e(csrf_token()) . '">';
}

/** Validate the token from a POST body or the X-CSRF header. Dies on failure. */
function csrf_check(): void
{
    $sent = $_POST['csrf'] ?? ($_SERVER['HTTP_X_CSRF'] ?? '');
    if (empty($_SESSION['csrf']) || !hash_equals($_SESSION['csrf'], (string)$sent)) {
        http_response_code(419);
        exit('Sesija pasibaigė arba forma nebegaliojanti. Grįžkite atgal ir bandykite dar kartą.');
    }
}

// ---------------------------------------------------------------------------
// Flash messages
// ---------------------------------------------------------------------------

function flash(string $msg, string $type = 'success'): void
{
    $_SESSION['flash'][] = ['msg' => $msg, 'type' => $type];
}

function flash_render(): string
{
    if (empty($_SESSION['flash'])) {
        return '';
    }
    $out = '';
    foreach ($_SESSION['flash'] as $f) {
        $out .= '<div class="flash flash-' . e($f['type']) . '">' . e($f['msg']) . '</div>';
    }
    unset($_SESSION['flash']);
    return $out;
}

// ---------------------------------------------------------------------------
// Page stub files  (about.php, gallery.php, … — thin wrappers around page.php)
// ---------------------------------------------------------------------------

function page_stub_path(string $slug): string
{
    return dirname(__DIR__) . '/' . $slug . '.php';
}

/** Create the physical .php file for a page slug. Returns true on success. */
function ensure_page_stub(string $slug): bool
{
    if ($slug === 'home' || !preg_match('/^[a-z0-9-]{1,80}$/', $slug)
        || in_array($slug, BW_RESERVED_SLUGS, true)) {
        return $slug === 'home'; // home is served by index.php, nothing to do
    }
    $code = "<?php\n// Auto-generated by Baltic Wave CMS — do not edit.\n"
          . "\$__slug = '" . $slug . "';\nrequire __DIR__ . '/page.php';\n";
    return (bool)@file_put_contents(page_stub_path($slug), $code);
}

/** Remove a page stub file (only if it looks auto-generated). */
function delete_page_stub(string $slug): void
{
    if ($slug === 'home' || !preg_match('/^[a-z0-9-]{1,80}$/', $slug)
        || in_array($slug, BW_RESERVED_SLUGS, true)) {
        return;
    }
    $path = page_stub_path($slug);
    if (is_file($path) && str_contains((string)@file_get_contents($path), 'Auto-generated by Baltic Wave CMS')) {
        @unlink($path);
    }
}

// ---------------------------------------------------------------------------
// Menu
// ---------------------------------------------------------------------------

/** Visible menu items as a tree: [ [item, children => []], … ] */
function menu_tree(): array
{
    $items = q_all('SELECT m.*, p.slug AS page_slug FROM menu_items m
                    LEFT JOIN pages p ON p.id = m.page_id
                    WHERE m.visible = 1
                    ORDER BY m.sort_order, m.id');
    $tree = [];
    $byId = [];
    foreach ($items as $it) {
        $it['children'] = [];
        $byId[$it['id']] = $it;
    }
    foreach ($byId as $id => $it) {
        if ($it['parent_id'] && isset($byId[$it['parent_id']])) {
            $byId[$it['parent_id']]['children'][] = &$byId[$id];
        } else {
            $tree[] = &$byId[$id];
        }
    }
    return $tree;
}

/** Resolve a menu item's target URL. */
function menu_item_url(array $item): string
{
    if (!empty($item['page_slug'])) {
        return page_url($item['page_slug']);
    }
    return $item['url'] ?: '#';
}
